baseURL = 'https://endorama.dev/'
# baseURL = 'https://endorama.github.io/'
languageCode = 'en-gb'
title = 'Edoardo Tenani'
theme = 'gokarna'

enableEmoji = true
enableRobotsTXT = true
paginate = 2
Copyright = "© Edoardo Tenani 2022 - Some Rights Reserved"
canonifyurls = true

[params]
  ShowSiteTitle = true
  metaKeywords = ["blog", "software", "engineer", "craft", "craftman", "developer"]
  footer = "Edoardo Tenani"
  description = "Software craftsman"
  
  accentColor = "#3689E6"
  
  socialIcons = [
      {name = "github", url = "https://github.com/endorama"},
      {name = "twitter", url = "https://twitter.com/edoardotenani"},
      {name = "linkedin", url = "https://www.linkedin.com/in/edoardotenani/"},
    #   {name = "stackoverflow", url = "https://example.com"},
    ]

  customHeadHTML = '''
    <link id="custom" rel="stylesheet" href="/css/override.css" />

    <!-- Pixel Code for https://app.tinyanalytics.io/ -->
    <script defer src="https://app.tinyanalytics.io/pixel/6Dm2gJFKAW2eahvV"></script>
    <!-- END Pixel Code -->
  '''

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 22

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 30

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 40

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/endorama"
    weight = 50

#   [[menu.main]]
#     identifier = "buymeacoffee"
#     pre = "<span data-feather='coffee'></span>"
#     url = "https://www.buymeacoffee.com/avijitgupta"
#     weight = 6

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 70